export const reports = [
  {
    id: 1,
    type: 'Flood',
    location: 'Kapitolyo, Pasig',
    status: 'Verified',
    time: '5 mins ago',
    icon: '🖼️',
    color: '#3B82F6',
    statusColor: '#10B981',
    bgColor: '#DBEAFE',
  },
  {
    id: 2,
    type: 'Fire',
    location: 'Ortigas, Pasig',
    status: 'Pending',
    time: '12 mins ago',
    icon: '🎥',
    color: '#F97316',
    statusColor: '#F59E0B',
    bgColor: '#FFEDD5',
  },
  {
    id: 3,
    type: 'Landslide',
    location: 'Rizal, Pasig',
    status: 'Verified',
    time: '1 hour ago',
    icon: '🖼️',
    color: '#92400E',
    statusColor: '#10B981',
    bgColor: '#FED7AA',
  },
];